User.create!([
  {email: "andyfirk@yahoo.com", encrypted_password: "$2a$11$c7xRmTnk2ROzDutk9exQQudHFcGzQdGPTKY3PsGyK6ZPGT.Lex1R.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 30, current_sign_in_at: "2017-03-03 19:01:44", last_sign_in_at: "2017-03-03 19:01:04", current_sign_in_ip: "::1", last_sign_in_ip: "::1", role: "admin"}
])
Event.create!([
  {name: "Asian Market Tour", location: "Mustang Flea Market", latitude: 27.8392161, longitude: -82.7469678, description: "<div>A brief description of event</div>", start_time: "2017-03-04 17:00:00", end_time: "2017-03-04 20:00:00", address: "7901 Park blvd N, Pinellas Park, FL 33781", poster: "tester.jpg"},
  {name: "Made Up Event", location: "Made Up Park", latitude: nil, longitude: nil, description: "<div>We will be camping! It will be great! Hooray!</div>", start_time: "2017-04-04 13:00:00", end_time: "2017-04-05 21:00:00", address: "", poster: nil},
  {name: "Wild Edible Plant Walk", location: "Myakka River State Park", latitude: 27.2395976, longitude: -82.316257, description: "<div><strong>This is a much larger event title<br></strong>We can add a bunch of content here so that it allows us to see some of the description details!<br><br></div><ul><li>a bulleted list</li><li>of what to bring</li><li>so that everybody knows this!</li></ul><pre>We can maybe add this for emphasis on something</pre><div>it would be nice to restyle the &lt;code&gt; sections so that they are much nicer and more relevant to Andy's website<br><br>anyways... maybe this description is long enough now!?<br><br></div><pre>This is an important message now!</pre><div><br><br></div><div><br></div>", start_time: "2017-04-02 13:00:00", end_time: "2017-04-02 20:00:00", address: "Myakka River State Park", poster: nil}
])
FarmsMap.create!([
  {name: "Inyoni Organic Farm", address: "960 Deer Run Ln Naples, FL 34120", latitude: 26.263179, longitude: -81.626581, description: "<div>Serving premium organic produce to the Naples area for over 5 years, Inyoni is home to some of the finest produce your money can buy!</div><ul><li>Serving premium organic produce to the Naples area for over 5 years, Inyoni is home to some of the finest produce your money can buy!</li><li>Serving premium organic produce to the Naples area for over 5 years, Inyoni is home to some of the finest produce your money can buy!</li></ul><blockquote>Serving premium organic produce to the Naples area for over 5 years, Inyoni is home to some of the finest produce your money can buy!</blockquote><div><strong>Serving premium organic produce to the Naples area for over 5 years, Inyoni is home to some of the finest produce your money can buy!<br><br></strong><a href=\"https://developers.google.com/maps/pricing-and-plans/#sup_3\"><strong>link to</strong></a><strong><br><br></strong><figure class=\"attachment attachment-preview\" data-trix-attachment=\"{&quot;contentType&quot;:&quot;image&quot;,&quot;height&quot;:426,&quot;url&quot;:&quot;https://s-media-cache-ak0.pinimg.com/originals/e3/16/61/e31661f31daebd5b4faaebf6785d980d.jpg&quot;,&quot;width&quot;:640}\" data-trix-content-type=\"image\"><img src=\"https://s-media-cache-ak0.pinimg.com/originals/e3/16/61/e31661f31daebd5b4faaebf6785d980d.jpg\" width=\"640\" height=\"426\"><figcaption class=\"caption\"></figcaption></figure></div>"},
  {name: "FruitScapes", address: "12870 Stringfellow Rd, Bokeelia, FL 33922", latitude: 26.6490426, longitude: -82.1251996, description: "<div>Fruit Scapes offers thousands of varieties of tropical fruits for south Florida. Be sure to check out their densely planted rows of mangoes! And their exquisite Jackfruit collection!</div>"},
  {name: "Bamboo Grove", address: "2460 SW Mixon St Arcadia, FL 34266", latitude: 27.147701, longitude: -81.883725, description: "<div>Bamboo Grove is a rich perennial garden with over 500 different species of edible, medicinal, and utilitarian plants!</div>"},
  {name: "Green Dreams", address: "15715 Mahoney Dr Spring Hill, FL 34610", latitude: 28.3859, longitude: -82.49834899999999, description: "<div>A permaculture homestead example to the ultimate! Pete Kanaris hosts this beautiful property which challenges to grow tropical plants well outside of their prescribed regions underneath a canopy of large beautiful oaks!</div>"}
])
Resource.create!([
  {binomial: "Camellia sasanqua", common: "Camellia", description: "<div><strong><em><br>Camellia</em></strong> is a <a href=\"https://en.wikipedia.org/wiki/Genus\">genus</a> of <a href=\"https://en.wikipedia.org/wiki/Flowering_plant\">flowering plants</a> in the <a href=\"https://en.wikipedia.org/wiki/Family_(biology)\">family</a> <a href=\"https://en.wikipedia.org/wiki/Theaceae\">Theaceae</a>. They are <a href=\"https://en.wikipedia.org/wiki/Native_plant\">found</a> in eastern and southern Asia, from the Himalayas east to Japan and Indonesia. There are 100–300 described <a href=\"https://en.wikipedia.org/wiki/Species\">species</a>, with some controversy over the exact number. There are also around 3,000 hybrids. The genus was named by <a href=\"https://en.wikipedia.org/wiki/Carl_Linnaeus\">Linnaeus</a> after the <a href=\"https://en.wikipedia.org/wiki/Jesuit\">Jesuit</a> botanist <a href=\"https://en.wikipedia.org/wiki/Georg_Joseph_Kamel\">Georg Joseph Kamel</a>, who worked in the Philippines and described a species of camellia (although Linnaeus did not refer to Kamel's account when discussing the genus).<a href=\"https://en.wikipedia.org/wiki/Camellia#cite_note-Kroupa2015-1\">[1]</a> Camellias are famous throughout East Asia; they are known as <em>cháhuā</em> (茶花) in Chinese, \"tea flower\", an apt designation, as <em>tsubaki</em> (椿) in Japanese, as <em>dongbaek-kkot</em> (동백꽃) in Korean and as <em>hoa trà</em> or <em>hoa chè</em> in Vietnamese.<br><br></div><div><br>Of economic importance in the Indian subcontinent and Asia, leaves of <a href=\"https://en.wikipedia.org/wiki/Camellia_sinensis\"><em>C. sinensis</em></a> are processed to create the popular beverage, <a href=\"https://en.wikipedia.org/wiki/Tea\">tea</a>. The ornamental <a href=\"https://en.wikipedia.org/wiki/Camellia_japonica\"><em>C. japonica</em></a>, <a href=\"https://en.wikipedia.org/wiki/Camellia_sasanqua\"><em>C. sasanqua</em></a> and their <a href=\"https://en.wikipedia.org/wiki/Hybrid_(biology)#Hybrid_plants\">hybrids</a> are the source of hundreds of garden <a href=\"https://en.wikipedia.org/wiki/Cultivar\">cultivars</a>. <a href=\"https://en.wikipedia.org/wiki/Camellia_oleifera\"><em>C. oleifera</em></a> produces <a href=\"https://en.wikipedia.org/wiki/Tea_seed_oil\">tea seed oil</a>, used in cooking.<br><br></div>"},
  {binomial: "Amorphophallus konjac", common: "Voodoo Lily", description: "<div><strong><br>Konjac</strong> (English pronunciation: <a href=\"https://en.wikipedia.org/wiki/Help:IPA_for_English\">/ˈkoʊnjæk/</a> <a href=\"https://en.wikipedia.org/wiki/Help:Pronunciation_respelling_key\"><strong><em>kohn</em></strong><em>-yak</em></a>; <strong><em>Amorphophallus konjac</em></strong>; <a href=\"https://en.wikipedia.org/wiki/Synonymy\">syn.</a> <em>A. rivieri</em>; <a href=\"https://en.wikipedia.org/wiki/Japanese_language\">Japanese</a>: 蒟蒻/菎蒻; こんにゃく; <strong><em>konnyaku</em></strong>; <a href=\"https://en.wikipedia.org/wiki/Korean_language\">Korean</a>: 곤약; <strong><em>gonyak</em></strong>; <a href=\"https://en.wikipedia.org/wiki/Chinese_language\">Chinese</a>: 蒟蒻; <a href=\"https://en.wikipedia.org/wiki/Pinyin\">pinyin</a>: <em>jǔruò</em>), also known as <strong>konjak</strong>, <strong>konjaku</strong>, <strong>konnyaku potato</strong>, <strong>devil's tongue</strong>, <strong>voodoo lily</strong>, <strong>snake palm</strong>, or <strong>elephant yam</strong> (though this name is also used for <a href=\"https://en.wikipedia.org/wiki/Amorphophallus_paeoniifolius\"><em>A. paeoniifolius</em></a>), is a plant of the genus <a href=\"https://en.wikipedia.org/wiki/Amorphophallus\"><em>Amorphophallus</em></a>.<br><br></div><div><br>It is native to warm subtropical to tropical eastern <a href=\"https://en.wikipedia.org/wiki/Asia\">Asia</a>, from <a href=\"https://en.wikipedia.org/wiki/Japan\">Japan</a> and <a href=\"https://en.wikipedia.org/wiki/China\">China</a> south to <a href=\"https://en.wikipedia.org/wiki/Indonesia\">Indonesia</a> (USDA hardiness Zone 6-11). It is a <a href=\"https://en.wikipedia.org/wiki/Perennial_plant\">perennial plant</a>, growing from a large <a href=\"https://en.wikipedia.org/wiki/Corm\">corm</a> up to 25 cm (10 in) in diameter. The single <a href=\"https://en.wikipedia.org/wiki/Leaf\">leaf</a> is up to 1.3 m (4 ft) across, <a href=\"https://en.wikipedia.org/wiki/Bipinnate\">bipinnate</a>, and divided into numerous leaflets.<a href=\"https://en.wikipedia.org/wiki/Konjac#cite_note-2\">[2]</a> The <a href=\"https://en.wikipedia.org/wiki/Flower\">flowers</a> are produced on a <a href=\"https://en.wikipedia.org/wiki/Spathe\">spathe</a> enclosed by a dark purple <a href=\"https://en.wikipedia.org/wiki/Spadix_(botany)\">spadix</a> up to 55 cm (22 in) long.<br><br></div>"},
  {binomial: "Binomial name", common: "Common Name", description: "<div>A short description which allows&nbsp;</div><h1>Rich Text!</h1><div>Aint that just special :)<br><br></div>"},
  {binomial: "Newius plantius", common: "A New Plant", description: "<div>This is a test plant to be sure that my images are still working correctly after mounting another uploader! Cross your fingies!</div>"},
  {binomial: "Newius vegetata", common: "Newest Plant", description: "<div>This is a new plant added to the database! Let's see how it plays along with the rest of the application</div>"}
])
ResourceAttachment.create!([
  {resource_id: 26, picture: "0709161403b.jpg", caption: "Stuff!", rotate: 270},
  {resource_id: 30, picture: "0629161256b.jpg", caption: "Emerging Leaves", rotate: 0},
  {resource_id: 30, picture: "0709161402.jpg", caption: "A different plant", rotate: 270},
  {resource_id: 26, picture: "0619161801.jpg", caption: "Just look at those!", rotate: 0},
  {resource_id: 31, picture: "0925161458a.jpg", caption: "Here's a caption", rotate: 90},
  {resource_id: 32, picture: "0719161121a.jpg", caption: "", rotate: 0},
  {resource_id: 35, picture: "0925161558.jpg", caption: "", rotate: 90}
])
